//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsClient.ProductsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductData", Namespace="http://schemas.datacontract.org/2004/07/ProductsServiceLibrary")]
    public partial class ProductData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ColorField;
        
        private decimal ListPriceField;
        
        private string NameField;
        
        private string ProductNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice
        {
            get
            {
                return this.ListPriceField;
            }
            set
            {
                this.ListPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber
        {
            get
            {
                return this.ProductNumberField;
            }
            set
            {
                this.ProductNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseFault", Namespace="http://schemas.datacontract.org/2004/07/ProductsServiceLibrary")]
    public partial class DatabaseFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DbMessageField;
        
        private string DbOperationField;
        
        private string DbReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DbMessage
        {
            get
            {
                return this.DbMessageField;
            }
            set
            {
                this.DbMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DbOperation
        {
            get
            {
                return this.DbOperationField;
            }
            set
            {
                this.DbOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DbReason
        {
            get
            {
                return this.DbReasonField;
            }
            set
            {
                this.DbReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFault", Namespace="http://schemas.datacontract.org/2004/07/ProductsServiceLibrary")]
    public partial class SystemFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SystemMessageField;
        
        private string SystemOperationField;
        
        private string SystemReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemMessage
        {
            get
            {
                return this.SystemMessageField;
            }
            set
            {
                this.SystemMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemOperation
        {
            get
            {
                return this.SystemOperationField;
            }
            set
            {
                this.SystemOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemReason
        {
            get
            {
                return this.SystemReasonField;
            }
            set
            {
                this.SystemReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ProductsServiceLibrary")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsClient.ProductsService.IProductsService")]
    public interface IProductsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/ListProducts", ReplyAction="http://tempuri.org/IProductsService/ListProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsClient.ProductsService.DatabaseFault), Action="http://tempuri.org/IProductsService/ListProductsDatabaseFaultFault", Name="DatabaseFault", Namespace="http://schemas.datacontract.org/2004/07/ProductsServiceLibrary")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsClient.ProductsService.SystemFault), Action="http://tempuri.org/IProductsService/ListProductsSystemFaultFault", Name="SystemFault", Namespace="http://schemas.datacontract.org/2004/07/ProductsServiceLibrary")]
        string[] ListProducts();
        
        //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/ListProducts", ReplyAction="http://tempuri.org/IProductsService/ListProductsResponse")]
        //System.Threading.Tasks.Task<string[]> ListProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProduct", ReplyAction="http://tempuri.org/IProductsService/GetProductResponse")]
        ProductsClient.ProductsService.ProductData GetProduct(string productNumber);
        
        //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/GetProduct", ReplyAction="http://tempuri.org/IProductsService/GetProductResponse")]
        //System.Threading.Tasks.Task<ProductsClient.ProductsService.ProductData> GetProductAsync(string productNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/CurrentStockLevel", ReplyAction="http://tempuri.org/IProductsService/CurrentStockLevelResponse")]
        int CurrentStockLevel(string productNumber);
        
        //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/CurrentStockLevel", ReplyAction="http://tempuri.org/IProductsService/CurrentStockLevelResponse")]
        //System.Threading.Tasks.Task<int> CurrentStockLevelAsync(string productNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/ChangeStockLevel", ReplyAction="http://tempuri.org/IProductsService/ChangeStockLevelResponse")]
        bool ChangeStockLevel(string productNumber, short newStockLevel, string shelf, int bin);
        
        //[System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsService/ChangeStockLevel", ReplyAction="http://tempuri.org/IProductsService/ChangeStockLevelResponse")]
        //System.Threading.Tasks.Task<bool> ChangeStockLevelAsync(string productNumber, short newStockLevel, string shelf, int bin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductsServiceChannel : ProductsClient.ProductsService.IProductsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsServiceClient : System.ServiceModel.ClientBase<ProductsClient.ProductsService.IProductsService>, ProductsClient.ProductsService.IProductsService
    {
        
        public ProductsServiceClient()
        {
        }
        
        public ProductsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string[] ListProducts()
        {
            return base.Channel.ListProducts();
        }
        
        //public System.Threading.Tasks.Task<string[]> ListProductsAsync()
        //{
        //    return base.Channel.ListProductsAsync();
        //}
        
        public ProductsClient.ProductsService.ProductData GetProduct(string productNumber)
        {
            return base.Channel.GetProduct(productNumber);
        }
        
        //public System.Threading.Tasks.Task<ProductsClient.ProductsService.ProductData> GetProductAsync(string productNumber)
        //{
        //    return base.Channel.GetProductAsync(productNumber);
        //}
        
        public int CurrentStockLevel(string productNumber)
        {
            return base.Channel.CurrentStockLevel(productNumber);
        }
        
        //public System.Threading.Tasks.Task<int> CurrentStockLevelAsync(string productNumber)
        //{
        //    return base.Channel.CurrentStockLevelAsync(productNumber);
        //}
        
        public bool ChangeStockLevel(string productNumber, short newStockLevel, string shelf, int bin)
        {
            return base.Channel.ChangeStockLevel(productNumber, newStockLevel, shelf, bin);
        }
        
        //public System.Threading.Tasks.Task<bool> ChangeStockLevelAsync(string productNumber, short newStockLevel, string shelf, int bin)
        //{
        //    return base.Channel.ChangeStockLevelAsync(productNumber, newStockLevel, shelf, bin);
        //}
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsClient.ProductsService.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ProductsClient.ProductsService.CompositeType GetDataUsingDataContract(ProductsClient.ProductsService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ProductsClient.ProductsService.CompositeType> GetDataUsingDataContractAsync(ProductsClient.ProductsService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProductsClient.ProductsService.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProductsClient.ProductsService.IService1>, ProductsClient.ProductsService.IService1
    {
        
        public Service1Client()
        {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public ProductsClient.ProductsService.CompositeType GetDataUsingDataContract(ProductsClient.ProductsService.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ProductsClient.ProductsService.CompositeType> GetDataUsingDataContractAsync(ProductsClient.ProductsService.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
